name: Coverage

on:
  workflow_call:
    secrets:
        CODECOV_TOKEN:
          required: true

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests with coverage
      run: |
        pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=xml:coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Traenqui/cicd-test-project
        fail_ci_if_error: false
